sudo: required

language: scala

jdk:
  - oraclejdk7

scala:
   - 2.9.2
   
before_install:
  - sudo perl -npi -e 's/^( *addSbt (warn|info).*)/#$1/g' /usr/local/bin/sbt

after_failure:
  - sbt dependency-tree